name: log-data

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 5,14 * * 1-5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  log-time-data:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: setup-node
        uses: actions/setup-node@master

      - name: create .env file
        run: |
          touch .env
          echo v1 = ${{ secrets.LOGIN_URL }} >> .env
          echo v2 = ${{ secrets.EMAIL }} >> .env
          echo v3 = ${{ secrets.PASSWORD }} >> .env
          echo v4 = ${{ secrets.LATITUDE }} >> .env
          echo v5 = ${{ secrets.LANGITUDE }} >> .env

      - name: installing dependencies
        run: |
          npm install

      - name: RUN JOB
        run: |
          node index.js
